### ISSUE TITLE
处理Json数据时出现错误

### ISSUE THREAD

**Issue by CBGan** [cqbef/cqhttp.WebSocketReverse.NETCore#1]
出错文件：CqHttpParse.cs
出错位置：Line 107
出错代码：`receivedDate = DateTimeOffset.FromUnixTimeSeconds(timestamp).AddHours(8).DateTime;`

修改为`receivedDate = DateTimeOffset.FromUnixTimeMilliseconds(timestamp).AddHours(8).DateTime;`后正常运行
cqhttp传的时间戳单位实际上是毫秒

**Comment by yyuueexxiinngg** [comment]
确认为`cqhttp-mirai`方的问题 https://github.com/yyuueexxiinngg/cqhttp-mirai/issues/70
